language: node_js
node_js:
  - "4"
  - "stable"
sudo: true
script: "gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=c7da13e8e21a746fd8b141db2d8d391914756b91a62bca5c78d93695e6b39827 codeclimate-test-reporter < lcov.info
